"""
Given an m x n board of characters and a list of strings words, return all words on the board.
Each word must be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once in a word.

Example 1:
Input: board = [["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]], words = ["oath","pea","eat","rain"]
Output: ["eat","oath"]

Example 2:
Input: board = [["a","b"],["c","d"]], words = ["abcb"]
Output: []

Constraints:
    m == board.length
    n == board[i].length
    1 <= m, n <= 12
    board[i][j] is a lowercase English letter.
    1 <= words.length <= 3 * 104
    1 <= words[i].length <= 10
    words[i] consists of lowercase English letters.
    All the strings of words are unique.
"""

from typing import List


class Trie:
    def __init__(self, val) -> None:
        self.val = val
        self.children = {}
        self.parent = None
        self.end = False
        self.found = False
        self.word = ""

    def __str__(self) -> str:
        return f"Trie {self.val or 'root'} children {self.children.keys()}"

    def insert(self, word):
        head = self
        for ch in word:
            if ch in head.children:
                head = head.children[ch]
                continue

            n = Trie(ch)
            n.parent = head
            head.children[ch] = n
            head = n

        head.end = True
        head.word = word

    def get_root(self):
        head = self
        while head.parent is not None:
            head = head.parent
        return head

    def remove(self, word):
        head = real = self
        i = 0
        while not head.end and head.word != word:
            head = head.children[word[i]]
            i += 1

        if head.children:
            head.end = False
            head.word = ""
            return real

        while head.parent is not None:
            if head.children:
                break
            p = head.parent
            del p.children[head.val]
            head = p
        return head


class Solution:
    def findWords(self, board: List[List[str]], words: List[str]) -> List[str]:
        rows, cols = len(board), len(board[0])

        def find_word(left, right, root: Trie):
            if (
                left < 0
                or right < 0
                or left > rows - 1
                or right > cols - 1
                or board[left][right] not in root.children
            ):
                return []

            child = root.children[board[left][right]]

            res = []
            if child.end and not child.found:
                child.found = True
                res.append(child.word)
                root = child.get_root()
                root.remove(child.word)

            if not child.children:
                return res

            org = board[left][right]
            board[left][right] = "-"

            res += find_word(left + 1, right, child)
            res += find_word(left, right + 1, child)
            res += find_word(left - 1, right, child)
            res += find_word(left, right - 1, child)

            board[left][right] = org
            return res

        trie = Trie("")
        for w in words:
            trie.insert(w)

        res = set()
        for l in range(rows):
            for r in range(cols):
                ch = board[l][r]
                if ch not in trie.children:
                    continue

                for w in find_word(l, r, trie):
                    res.add(w)

        return list(res)


if __name__ == "__main__":
    assert (
        set(
            Solution().findWords(
                board=[
                    ["o", "a", "a", "n"],
                    ["e", "t", "a", "e"],
                    ["i", "h", "k", "r"],
                    ["i", "f", "l", "v"],
                ],
                words=["oath", "pea", "eat", "rain"],
            )
        )
        == set(["eat", "oath"])
    )
    assert (
        set(
            Solution().findWords(
                board=[
                    ["o", "a", "b", "n"],
                    ["o", "t", "a", "e"],
                    ["a", "h", "k", "r"],
                    ["a", "f", "l", "v"],
                ],
                words=["oa", "oaa"],
            )
        )
        == set(["oa", "oaa"])
    )
    assert (
        set(
            Solution().findWords(
                board=[
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                ],
                words=[
                    "ababababaa",
                    "ababababab",
                    "ababababac",
                    "ababababad",
                    "ababababae",
                    "ababababaf",
                    "ababababag",
                    "ababababah",
                    "ababababai",
                    "ababababaj",
                    "ababababak",
                    "ababababal",
                    "ababababam",
                    "ababababan",
                    "ababababao",
                    "ababababap",
                    "ababababaq",
                    "ababababar",
                    "ababababas",
                    "ababababat",
                    "ababababau",
                    "ababababav",
                    "ababababaw",
                    "ababababax",
                    "ababababay",
                    "ababababaz",
                    "ababababba",
                    "ababababbb",
                    "ababababbc",
                    "ababababbd",
                    "ababababbe",
                    "ababababbf",
                    "ababababbg",
                    "ababababbh",
                    "ababababbi",
                    "ababababbj",
                    "ababababbk",
                    "ababababbl",
                    "ababababbm",
                    "ababababbn",
                    "ababababbo",
                    "ababababbp",
                    "ababababbq",
                    "ababababbr",
                    "ababababbs",
                    "ababababbt",
                    "ababababbu",
                    "ababababbv",
                    "ababababbw",
                    "ababababbx",
                    "ababababby",
                    "ababababbz",
                    "ababababca",
                    "ababababcb",
                    "ababababcc",
                    "ababababcd",
                    "ababababce",
                    "ababababcf",
                    "ababababcg",
                    "ababababch",
                    "ababababci",
                    "ababababcj",
                    "ababababck",
                    "ababababcl",
                    "ababababcm",
                    "ababababcn",
                    "ababababco",
                    "ababababcp",
                    "ababababcq",
                    "ababababcr",
                    "ababababcs",
                    "ababababct",
                    "ababababcu",
                    "ababababcv",
                    "ababababcw",
                    "ababababcx",
                    "ababababcy",
                    "ababababcz",
                    "ababababda",
                    "ababababdb",
                    "ababababdc",
                    "ababababdd",
                    "ababababde",
                    "ababababdf",
                    "ababababdg",
                    "ababababdh",
                    "ababababdi",
                    "ababababdj",
                    "ababababdk",
                    "ababababdl",
                    "ababababdm",
                    "ababababdn",
                    "ababababdo",
                    "ababababdp",
                    "ababababdq",
                    "ababababdr",
                    "ababababds",
                    "ababababdt",
                    "ababababdu",
                    "ababababdv",
                    "ababababdw",
                    "ababababdx",
                    "ababababdy",
                    "ababababdz",
                    "ababababea",
                    "ababababeb",
                    "ababababec",
                    "ababababed",
                    "ababababee",
                    "ababababef",
                    "ababababeg",
                    "ababababeh",
                    "ababababei",
                    "ababababej",
                    "ababababek",
                    "ababababel",
                    "ababababem",
                    "ababababen",
                    "ababababeo",
                    "ababababep",
                    "ababababeq",
                    "ababababer",
                    "ababababes",
                    "ababababet",
                    "ababababeu",
                    "ababababev",
                    "ababababew",
                    "ababababex",
                    "ababababey",
                    "ababababez",
                    "ababababfa",
                    "ababababfb",
                    "ababababfc",
                    "ababababfd",
                    "ababababfe",
                    "ababababff",
                    "ababababfg",
                    "ababababfh",
                    "ababababfi",
                    "ababababfj",
                    "ababababfk",
                    "ababababfl",
                    "ababababfm",
                    "ababababfn",
                    "ababababfo",
                    "ababababfp",
                    "ababababfq",
                    "ababababfr",
                    "ababababfs",
                    "ababababft",
                    "ababababfu",
                    "ababababfv",
                    "ababababfw",
                    "ababababfx",
                    "ababababfy",
                    "ababababfz",
                    "ababababga",
                    "ababababgb",
                    "ababababgc",
                    "ababababgd",
                    "ababababge",
                    "ababababgf",
                    "ababababgg",
                    "ababababgh",
                    "ababababgi",
                    "ababababgj",
                    "ababababgk",
                    "ababababgl",
                    "ababababgm",
                    "ababababgn",
                    "ababababgo",
                    "ababababgp",
                    "ababababgq",
                    "ababababgr",
                    "ababababgs",
                    "ababababgt",
                    "ababababgu",
                    "ababababgv",
                    "ababababgw",
                    "ababababgx",
                    "ababababgy",
                    "ababababgz",
                    "ababababha",
                    "ababababhb",
                    "ababababhc",
                    "ababababhd",
                    "ababababhe",
                    "ababababhf",
                    "ababababhg",
                    "ababababhh",
                    "ababababhi",
                    "ababababhj",
                    "ababababhk",
                    "ababababhl",
                    "ababababhm",
                    "ababababhn",
                    "ababababho",
                    "ababababhp",
                    "ababababhq",
                    "ababababhr",
                    "ababababhs",
                    "ababababht",
                    "ababababhu",
                    "ababababhv",
                    "ababababhw",
                    "ababababhx",
                    "ababababhy",
                    "ababababhz",
                    "ababababia",
                    "ababababib",
                    "ababababic",
                    "ababababid",
                    "ababababie",
                    "ababababif",
                    "ababababig",
                    "ababababih",
                    "ababababii",
                    "ababababij",
                    "ababababik",
                    "ababababil",
                    "ababababim",
                    "ababababin",
                    "ababababio",
                    "ababababip",
                    "ababababiq",
                    "ababababir",
                    "ababababis",
                    "ababababit",
                    "ababababiu",
                    "ababababiv",
                    "ababababiw",
                    "ababababix",
                    "ababababiy",
                    "ababababiz",
                    "ababababja",
                    "ababababjb",
                    "ababababjc",
                    "ababababjd",
                    "ababababje",
                    "ababababjf",
                    "ababababjg",
                    "ababababjh",
                    "ababababji",
                    "ababababjj",
                    "ababababjk",
                    "ababababjl",
                    "ababababjm",
                    "ababababjn",
                    "ababababjo",
                    "ababababjp",
                    "ababababjq",
                    "ababababjr",
                    "ababababjs",
                    "ababababjt",
                    "ababababju",
                    "ababababjv",
                    "ababababjw",
                    "ababababjx",
                    "ababababjy",
                    "ababababjz",
                    "ababababka",
                    "ababababkb",
                    "ababababkc",
                    "ababababkd",
                    "ababababke",
                    "ababababkf",
                    "ababababkg",
                    "ababababkh",
                    "ababababki",
                    "ababababkj",
                    "ababababkk",
                    "ababababkl",
                    "ababababkm",
                    "ababababkn",
                    "ababababko",
                    "ababababkp",
                    "ababababkq",
                    "ababababkr",
                    "ababababks",
                    "ababababkt",
                    "ababababku",
                    "ababababkv",
                    "ababababkw",
                    "ababababkx",
                    "ababababky",
                    "ababababkz",
                    "ababababla",
                    "abababablb",
                    "abababablc",
                    "ababababld",
                    "abababable",
                    "abababablf",
                    "abababablg",
                    "abababablh",
                    "ababababli",
                    "abababablj",
                    "abababablk",
                    "ababababll",
                    "abababablm",
                    "ababababln",
                    "abababablo",
                    "abababablp",
                    "abababablq",
                    "abababablr",
                    "ababababls",
                    "abababablt",
                    "abababablu",
                    "abababablv",
                    "abababablw",
                    "abababablx",
                    "abababably",
                    "abababablz",
                    "ababababma",
                    "ababababmb",
                    "ababababmc",
                    "ababababmd",
                    "ababababme",
                    "ababababmf",
                    "ababababmg",
                    "ababababmh",
                    "ababababmi",
                    "ababababmj",
                    "ababababmk",
                    "ababababml",
                    "ababababmm",
                    "ababababmn",
                    "ababababmo",
                    "ababababmp",
                    "ababababmq",
                    "ababababmr",
                    "ababababms",
                    "ababababmt",
                    "ababababmu",
                    "ababababmv",
                    "ababababmw",
                    "ababababmx",
                    "ababababmy",
                    "ababababmz",
                    "ababababna",
                    "ababababnb",
                    "ababababnc",
                    "ababababnd",
                    "ababababne",
                    "ababababnf",
                    "ababababng",
                    "ababababnh",
                    "ababababni",
                    "ababababnj",
                    "ababababnk",
                    "ababababnl",
                    "ababababnm",
                    "ababababnn",
                    "ababababno",
                    "ababababnp",
                    "ababababnq",
                    "ababababnr",
                    "ababababns",
                    "ababababnt",
                    "ababababnu",
                    "ababababnv",
                    "ababababnw",
                    "ababababnx",
                    "ababababny",
                    "ababababnz",
                    "ababababoa",
                    "ababababob",
                    "ababababoc",
                    "ababababod",
                    "ababababoe",
                    "ababababof",
                    "ababababog",
                    "ababababoh",
                    "ababababoi",
                    "ababababoj",
                    "ababababok",
                    "ababababol",
                    "ababababom",
                    "ababababon",
                    "ababababoo",
                    "ababababop",
                    "ababababoq",
                    "ababababor",
                    "ababababos",
                    "ababababot",
                    "ababababou",
                    "ababababov",
                    "ababababow",
                    "ababababox",
                    "ababababoy",
                    "ababababoz",
                    "ababababpa",
                    "ababababpb",
                    "ababababpc",
                    "ababababpd",
                    "ababababpe",
                    "ababababpf",
                    "ababababpg",
                    "ababababph",
                    "ababababpi",
                    "ababababpj",
                    "ababababpk",
                    "ababababpl",
                    "ababababpm",
                    "ababababpn",
                    "ababababpo",
                    "ababababpp",
                    "ababababpq",
                    "ababababpr",
                    "ababababps",
                    "ababababpt",
                    "ababababpu",
                    "ababababpv",
                    "ababababpw",
                    "ababababpx",
                    "ababababpy",
                    "ababababpz",
                    "ababababqa",
                    "ababababqb",
                    "ababababqc",
                    "ababababqd",
                    "ababababqe",
                    "ababababqf",
                    "ababababqg",
                    "ababababqh",
                    "ababababqi",
                    "ababababqj",
                    "ababababqk",
                    "ababababql",
                    "ababababqm",
                    "ababababqn",
                    "ababababqo",
                    "ababababqp",
                    "ababababqq",
                    "ababababqr",
                    "ababababqs",
                    "ababababqt",
                    "ababababqu",
                    "ababababqv",
                    "ababababqw",
                    "ababababqx",
                    "ababababqy",
                    "ababababqz",
                    "ababababra",
                    "ababababrb",
                    "ababababrc",
                    "ababababrd",
                    "ababababre",
                    "ababababrf",
                    "ababababrg",
                    "ababababrh",
                    "ababababri",
                    "ababababrj",
                    "ababababrk",
                    "ababababrl",
                    "ababababrm",
                    "ababababrn",
                    "ababababro",
                    "ababababrp",
                    "ababababrq",
                    "ababababrr",
                    "ababababrs",
                    "ababababrt",
                    "ababababru",
                    "ababababrv",
                    "ababababrw",
                    "ababababrx",
                    "ababababry",
                    "ababababrz",
                    "ababababsa",
                    "ababababsb",
                    "ababababsc",
                    "ababababsd",
                    "ababababse",
                    "ababababsf",
                    "ababababsg",
                    "ababababsh",
                    "ababababsi",
                    "ababababsj",
                    "ababababsk",
                    "ababababsl",
                    "ababababsm",
                    "ababababsn",
                    "ababababso",
                    "ababababsp",
                    "ababababsq",
                    "ababababsr",
                    "ababababss",
                    "ababababst",
                    "ababababsu",
                    "ababababsv",
                    "ababababsw",
                    "ababababsx",
                    "ababababsy",
                    "ababababsz",
                    "ababababta",
                    "ababababtb",
                    "ababababtc",
                    "ababababtd",
                    "ababababte",
                    "ababababtf",
                    "ababababtg",
                    "ababababth",
                    "ababababti",
                    "ababababtj",
                    "ababababtk",
                    "ababababtl",
                    "ababababtm",
                    "ababababtn",
                    "ababababto",
                    "ababababtp",
                    "ababababtq",
                    "ababababtr",
                    "ababababts",
                    "ababababtt",
                    "ababababtu",
                    "ababababtv",
                    "ababababtw",
                    "ababababtx",
                    "ababababty",
                    "ababababtz",
                    "ababababua",
                    "ababababub",
                    "ababababuc",
                    "ababababud",
                    "ababababue",
                    "ababababuf",
                    "ababababug",
                    "ababababuh",
                    "ababababui",
                    "ababababuj",
                    "ababababuk",
                    "ababababul",
                    "ababababum",
                    "ababababun",
                    "ababababuo",
                    "ababababup",
                    "ababababuq",
                    "ababababur",
                    "ababababus",
                    "ababababut",
                    "ababababuu",
                    "ababababuv",
                    "ababababuw",
                    "ababababux",
                    "ababababuy",
                    "ababababuz",
                    "ababababva",
                    "ababababvb",
                    "ababababvc",
                    "ababababvd",
                    "ababababve",
                    "ababababvf",
                    "ababababvg",
                    "ababababvh",
                    "ababababvi",
                    "ababababvj",
                    "ababababvk",
                    "ababababvl",
                    "ababababvm",
                    "ababababvn",
                    "ababababvo",
                    "ababababvp",
                    "ababababvq",
                    "ababababvr",
                    "ababababvs",
                    "ababababvt",
                    "ababababvu",
                    "ababababvv",
                    "ababababvw",
                    "ababababvx",
                    "ababababvy",
                    "ababababvz",
                    "ababababwa",
                    "ababababwb",
                    "ababababwc",
                    "ababababwd",
                    "ababababwe",
                    "ababababwf",
                    "ababababwg",
                    "ababababwh",
                    "ababababwi",
                    "ababababwj",
                    "ababababwk",
                    "ababababwl",
                    "ababababwm",
                    "ababababwn",
                    "ababababwo",
                    "ababababwp",
                    "ababababwq",
                    "ababababwr",
                    "ababababws",
                    "ababababwt",
                    "ababababwu",
                    "ababababwv",
                    "ababababww",
                    "ababababwx",
                    "ababababwy",
                    "ababababwz",
                    "ababababxa",
                    "ababababxb",
                    "ababababxc",
                    "ababababxd",
                    "ababababxe",
                    "ababababxf",
                    "ababababxg",
                    "ababababxh",
                    "ababababxi",
                    "ababababxj",
                    "ababababxk",
                    "ababababxl",
                    "ababababxm",
                    "ababababxn",
                    "ababababxo",
                    "ababababxp",
                    "ababababxq",
                    "ababababxr",
                    "ababababxs",
                    "ababababxt",
                    "ababababxu",
                    "ababababxv",
                    "ababababxw",
                    "ababababxx",
                    "ababababxy",
                    "ababababxz",
                    "ababababya",
                    "ababababyb",
                    "ababababyc",
                    "ababababyd",
                    "ababababye",
                    "ababababyf",
                    "ababababyg",
                    "ababababyh",
                    "ababababyi",
                    "ababababyj",
                    "ababababyk",
                    "ababababyl",
                    "ababababym",
                    "ababababyn",
                    "ababababyo",
                    "ababababyp",
                    "ababababyq",
                    "ababababyr",
                    "ababababys",
                    "ababababyt",
                    "ababababyu",
                    "ababababyv",
                    "ababababyw",
                    "ababababyx",
                    "ababababyy",
                    "ababababyz",
                    "ababababza",
                    "ababababzb",
                    "ababababzc",
                    "ababababzd",
                    "ababababze",
                    "ababababzf",
                    "ababababzg",
                    "ababababzh",
                    "ababababzi",
                    "ababababzj",
                    "ababababzk",
                    "ababababzl",
                    "ababababzm",
                    "ababababzn",
                    "ababababzo",
                    "ababababzp",
                    "ababababzq",
                    "ababababzr",
                    "ababababzs",
                    "ababababzt",
                    "ababababzu",
                    "ababababzv",
                    "ababababzw",
                    "ababababzx",
                    "ababababzy",
                    "ababababzz",
                ],
            )
        )
        == set(["oa", "oaa"])
    )
